
name: Build sample BuildPulse project

on:
  workflow_dispatch:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest --junitxml=reports/junit.xml
    - name: Upload test results to BuildPulse for flaky test detection
      if: '!cancelled()' # Run this step even when the tests fail. Skip if the workflow is cancelled.
      uses: buildpulse/buildpulse-action@main
      with:
        account: <buildpulse-account-id>
        repository: <buildpulse-repository-id>
        path: |
          reports/junit.xml # <path-to-xml-reports>
          reports2/**/junit.xml # support double globbing (if your github-hosted runner OS uses bash 4+)
        key: ${{ secrets.BUILDPULSE_ACCESS_KEY_ID }}
        secret: ${{ secrets.BUILDPULSE_SECRET_ACCESS_KEY }}
        coverage-files: coverage/report.xml # IF PURCHASED
        tags: e2e team1 staging # OPTIONAL
